import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import React, { useState } from 'react';


export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Watch Only</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
         <h1 className={styles.title}>
          Watch Only
        </h1>

        <p className={styles.description}>
          Counterparty Address Explorer
        </p>

        <div className={styles.grid}>
          <Link href="/create">
        <div className={styles.card}>
   
            <h2>Create Address List &rarr;</h2>
            <p>Add all of your addresses to your collection.</p>
     
      
        </div>
        </Link>
{/*       
        <a href="#" className={styles.card}>
            <h2>Explore Collection &rarr;</h2>
            <p>View and organize your collection.</p>
          </a>

            <a href="#" className={styles.card}>
            <h2>Import Data &rarr;</h2>
            <p>Load previously exported collections.</p>
          </a>
      
          <a href="#" className={styles.card}>
            <h2>Export Data &rarr;</h2>
            <p>Save your collection data for use with other applications.</p>
          </a> */}

         
        </div>
      </main>

    </div>
  )
}
